# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: skate-ipsum
    repository:
      owner: madflow
      name: homebrew-skate-ipsum
    url_template: "https://github.com/madflow/skate-ipsum/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    homepage: "https://github.com/madflow/skate-ipsum"
    description: "Skate Ipsum is a tool for generating random skateboarding related text."
    license: "MIT"
    test: |
      system "#{bin}/skate-ipsum"
    install: |
      bin.install "skate-ipsum"

nfpms:
  - formats:
      - apk
      - deb
      - rpm
      - archlinux
    vendor: "skate-ipsum.localhost"
    homepage: "https://github.com/madflow/skate-ipsum"
    maintainer: "madflow"
    description: "Skate Ipsum is a tool for generating random skateboarding related text."
    license: "MIT"
    file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"

scoops:
  - name: skate-ipsum
    repository:
      owner: madflow
      name: scoop-bucket
    description: "Skate Ipsum is a tool for generating random skateboarding related text."
    homepage: "https://github.com/madflow/skate-ipsum"
    license: MIT

aurs:
  - name: skate-ipsum

    homepage: "https://github.com/madflow/skate-ipsum"

    description: "Skate Ipsum is a tool for generating random skateboarding related text."

    provides:
      - skate-ipsum

    conflicts:
      - skate-ipsum

    maintainers:
      - "madflow"

    license: "MIT"

    private_key: "{{ .Env.AUR_KEY }}"

    git_url: "ssh://aur@aur.archlinux.org/skate-ipsum-bin.git"

    skip_upload: auto

    package: |-
      # bin
      install -Dm755 "./skate-ipsum" "${pkgdir}/usr/bin/skate-ipsum"

    commit_author:
      name: Skate Ipsum Releaser
      email: aur@skate-ipsum

dockers:
  - ids:
      - skate-ipsum
    goos: linux
    goarch: amd64
    image_templates:
      - "gcr.io/madflow/skate-ipsum:{{ .Tag }}-amd64"
      - "gcr.io/madflow/skate-ipsum:v{{ .Major }}-amd64"
      - "gcr.io/madflow/skate-ipsum:v{{ .Major }}.{{ .Minor }}-amd64"
      - "gcr.io/madflow/skate-ipsum:latest-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - ids:
      - centrifugo
    goos: linux
    goarch: arm64
    image_templates:
      - "gcr.io/madflow/skate-ipsum:{{ .Tag }}-arm64v8"
      - "gcr.io/madflow/skate-ipsum:v{{ .Major }}-arm64v8"
      - "gcr.io/madflow/skate-ipsum:v{{ .Major }}.{{ .Minor }}-arm64v8"
      - "gcr.io/madflow/skate-ipsum:latest-arm64v8"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64/v8"

docker_manifests:
  - name_template: madflow/skate-ipsum:{{ .Tag }}
    image_templates:
      - madflow/skate-ipsum:{{ .Tag }}-arm64v8
      - madflow/skate-ipsum:{{ .Tag }}-amd64
  - name_template: madflow/skate-ipsum:v{{ .Major }}
    image_templates:
      - madflow/skate-ipsum:{{ .Tag }}-arm64v8
      - madflow/skate-ipsum:{{ .Tag }}-amd64
  - name_template: madflow/skate-ipsum:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - madflow/skate-ipsum:{{ .Tag }}-arm64v8
      - madflow/skate-ipsum:{{ .Tag }}-amd64
  - name_template: madflow/skate-ipsum:latest
    image_templates:
      - madflow/skate-ipsum:{{ .Tag }}-arm64v8
      - madflow/skate-ipsum:{{ .Tag }}-amd64

release:
  footer: |
    **Full Changelog**: https://github.com/madflow/skate-ipsum/compare/{{ .PreviousTag }}...{{ .Tag }}

    ```
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxddkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlc::cccdKMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkcldddddo::d0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMWNKKXWMMMMMM0c:c:::lddo:.:KMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMXxoc::coxXMMMNo;cloo:cddool::xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMWO::clllol:c0MWk:colllcodo;;lol;;dkxdxkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMKccdoolcool;cKKc:lloooddl,..;coc;:c::;''lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMO::olll:;lc;,cOl;ldddol;.....,ccccloddo:.;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMO:cllllccoc,;,:kxc:;,'......,;cccc;cddddl':XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMO:clloddddc.'c;;ONK00o.....,:coollloddoclc':0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMk:lddddddl'..cd:,dNMMNx'..coooddddddoc'.cdl,'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMNd;:lolc;...,odo:'dWMMWO'.codddddoc;'..'lddo;.;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMW0d:'....'',ldl;.,0MMWd,::;,,,,'......:ddddo,.,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMK:...,;;codo:..xWMO;:ddollccc'.''..,:llodl..;dollkXWMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMM0,.,lodddddo,.cXNl,odddddddo'.lc.'..':ll;';looc'.;0MMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMW0,.cdddddddl..xO;:ddddddddc...'cdoc:::::::odddo;.lNMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWk',odoolcc:. ','cdddddddo,...cdo:;::cllccldl;ll.:XMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWx';lcc:;;::;;;,,;;;:cccl:...cddo;;odoclodo:..co,,OWMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMK;,l:::cloolc::c:,';cccc;'..;odddo;,;clc:;....ldc.'xNMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMWX00XWMMMMMMMWo':::ldddddlccodoc;,;lodoc:,.,ldddl' .::....'cddo;..lXMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMWKxo:,,'lKMMMMMMK;'cldocc:::ccllodddoc::codooc,,cdl,..:Ol'...,::cc;...kMMMMMMMMMMMMMMMMMM
    MMMMMMWXkdol::c;co,.lNMMMMM0'.ldocdOdlkOxcoo::loddolccllooc::,...,;:ol:;,;;,....lXMMMMMMMMMMMMMMMMMM
    MMMNKxl:..:lddc:od;.;KMMMMM0,.;dldNWKKWWK0WKlldccddddl,..;odoc;,..;oddddddl,..;kNMMMMMMMMMMMMMMMMMMM
    WKxoc:lo,'cllolldc..lNMMMMM0, ;dllOOlo0k:lOc,dk;.;coddo;.'ldddddl:;;cdddo:...lXMMMMMMMMMMMMMMMMMMMMM
    Kl:oddddl::loddo:..:KMMMMMM0'.cdocc'...............'lddo;,oddddddddc;col,...;KMMMMMMMMMMMMMMMMMMMMMM
    k;;cdddddddddo:'..oXMMMMMMNl.'oocld;................'lddo:cdddddddddc'''...,OWMMMMMMMMMMMMMMMMMMMMMM
    K:,loddddddo:....;0MMMMMMWx..:dc,cd;.................,oddl;codddddddl.....cKWMMMMMMMMMMMMMMMMMMMMMMM
    Wk';oddddddl,.....,kWMMNx:..;oo,.lo,..................cddd:',cddddddl'....xWMMMMMMMMMMMMMMMMMMMMMMMM
    MWx,cddolc;'..';'...oKk;...'co;.'ol. .................:dddc..'ldddol;.....xWMMMMMMMMMMMMMMMMMMMMMMMM
    MMWkcldoc:::clo:.....''..';lod,.:o;...................ldddc...cdddl;....cONMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMWO;;oddddol::clc,..;loodddd;.,,........'''........,odddc',lddddo;...cNMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMWd.cddddoloddddo,.cdddoc;,''',,,'',,,'...........lddddllodddddo;...,0MMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMK;'oddddddddddo;;ddddl...,,,,,,''............ .cdddddddddddddl,...,0MMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMWx',ldddddddddlcoddddoc'.....................':ddddddddddddddc...:0WMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMNo..;loddddoooddddddddlcc,.................:oddddddddddddddd:..cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMNo...:dddl:lddddddddolc;'''..............,odddddddddddddddo,..lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMWx'..,colcldddddddlo0klxXk':0x,,c'.''...:dddddddddddddddd:...cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMWKl....;ldddddddd::kkokXO:c0XldWk;x0:':odolldddddddddddl'. .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMW0l'..;oddddddoolllloddoooo:cxo':x:'cdc;,cddddddddddo;...cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMWXk:.,lddddl:looooooooooddolcc:ccodl'..;odddddddddc....;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMXl..cdddo:,''........,;;:looolc;....'lddddddddl'.....;xKWMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMNd..;odoclc::::,................. .:ddddddddl,........';cldk0XWMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMWO;..:lclccoollc,'..;cc:::'',,,;;:ldddddddc'..'loc;;,.......';cdOXWMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMNx,..,clll::llll:;lolcllcclllllccoddddo:'..;oddddddlc:::,'.....':oONMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMNx:..':clloool:coo:,;:clllllllllodoc'..'codddddddddddddoc:;'.....;dKMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMN0o;...,;:cclllloc,..',,,;;;;;,''..;codddddddddddddddddddolc;'...dWMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMN0dc'......':lddl:,,''''''''',:lddddddddddddddddddddddddddolc,lXMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo,....'',;;:odoc::;;;;:coddddddddddddddddddddddddddddddcdNMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxc;,.....;cc;,;:cc;'',;:clddddddddddddddddddddddddddo:dNMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXkl;'.'cll:'.':ll:,''':lodolcloddddddddddddddddlc,,dXMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXKOc'':cc:,',;:cllooodol:::::looc:coddddddl,''.':kNMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd'...':c:,'',;:ccodddddocclool::cc:cloc;:,...,kWMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxc:,..,col::;;::ccccloddddddddl;;;:c,;olol:,;xNMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKko;,:ll:;,'..:c::cloddddd:...'';docOWWNKXWMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxc::cddoc,,:ldolodddo;,......,dO0KXNMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc,;lddc;;;codddo;. .......;dxxkkxx0WMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;.':lodl::lol,.;odo,.',,:0WWWWNkloKWMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc,,;:cc;;;':;;oOXXxllooONXdoONNkxOXW
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0kkkxOkcxNd;lddx0OookNW0loXMMMMWM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMOl0WKkddONWMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKNMMMWKxoOWMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0WMMMW0kNMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0lOWMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXMMMMMMMMMMMMMMMMMM
    ```
